---
- name: Install Java
  hosts: all
  become: true
  remote_user: ubuntu

  vars:
    public_key_path: "/devops-tools/jenkins/id_rsa.pub"
    source_dir: files
    dest_dir: /home/ubuntu/
    files:
      - config.yml
      - properties.py
      - script.sh

  roles:
    - java