---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Fix broken packages
  become: true
  apt:
    name: ""
    state: present
    fix_broken: yes

- name: Install JRE
  become: true
  apt:
    name: openjdk-17-jre
    state: latest

- name: Create log file
  become: true
  file:
    path: /var/log/petclinic.log
    state: touch
    mode: '0777'
