---
- name: Update package lists
  become: true
  apt:
      update_cache: yes

- name: Install JDK
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Create log file
  become: true
  file:
    path: /var/log/petclinic.log
    state: touch
    mode: '0777'
