---
- name: Update package lists
  become: true
  apt:
      update_cache: yes

- name: Install JDK
  become: true
  apt:
      name: default-jdk
      state: present

- name: Create log file
  become: true
  file:
    path: /var/log/petclinic.log
    state: touch
    mode: '0777'
